# Generated by Django 4.0.5 on 2022-07-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_category_usercomments_alter_menu_imgpath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='menu',
            name='imgPath',
            field=models.URLField(blank=True),
        ),
    ]
