# Generated by Django 4.0.5 on 2022-07-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_category_imgpath_alter_menu_comment_userorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
