# Generated by Django 4.0.5 on 2022-07-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='item',
        ),
        migrations.AddField(
            model_name='userorder',
            name='items',
            field=models.JSONField(default=[]),
        ),
    ]
