# Generated by Django 4.0.5 on 2022-07-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_alter_userorder_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='items',
            field=models.JSONField(default=[{'item': '', 'price': 0, 'quantity': 0}]),
        ),
    ]
