# Generated by Django 4.0.5 on 2022-07-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_alter_userorder_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='status',
            field=models.CharField(blank=True, choices=[('c', 'Completed'), ('x', 'Cancelled'), ('p', 'Pending')], default='p', max_length=1),
        ),
    ]
