# Generated by Django 4.0.5 on 2022-07-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_alter_userorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='grandTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
