# Generated by Django 4.0.5 on 2022-07-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_userorder_grandtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='Completed', max_length=15),
        ),
    ]
