# Generated by Django 4.0.5 on 2022-07-02 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_alter_userorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='items',
            field=models.JSONField(default=[{'item': '', 'price': 0, 'quantity': 0}], validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
