# Generated by Django 4.0.5 on 2022-07-02 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_alter_userorder_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='items',
            field=models.JSONField(default=[{'item': '', 'price': 0, 'quantity': 0}], validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
