# Generated by Django 4.0.5 on 2022-07-07 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0015_alter_userorder_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='comment',
        ),
        migrations.AddField(
            model_name='usercomments',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.menu'),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='comment',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
