# Generated by Django 4.0.5 on 2022-07-07 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_remove_menu_comment_usercomments_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomments',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
            preserve_default=False,
        ),
    ]
