# Generated by Django 4.0.5 on 2022-07-07 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_usercomments_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomments',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
