# Generated by Django 4.0.5 on 2022-07-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_alter_usercomments_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='orderKey',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
